name: ACM-fig
channels:
  - anaconda
  - defaults
dependencies:
  - matplotlib=3.3.1
  - numpy=1.19.1
  - scikit-image=0.17.2
  - scipy=1.5.2
  - pip=20.2.4
  - python=3.7.9
  - pytorch=1.5.0
  - pip:
      - jax==0.2.21
      - jaxlib==0.1.71
      - mayavi==4.7.3
      - vtk==8.1.2


